/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ddb7ff",
        "surface-container-lowest": "#0b0d1b",
        "surface-container-low": "#191b29",
        "surface-container": "#1d1f2d",
        "surface-container-high": "#272938",
        "surface-container-highest": "#323443",
        "surface-bright": "#363848",
        "surface-dim": "#101221",
        "surface": "#101221",
        "surface-variant": "#323443",
        "background": "#101221",
        "on-background": "#e1e1f5",
        "on-surface": "#e1e1f5",
        "on-surface-variant": "#cfc2d6",
        "inverse-surface": "#e1e1f5",
        "inverse-on-surface": "#2e2f3f",
        "outline": "#988d9f",
        "outline-variant": "#4d4354",
        "primary": "#ddb7ff",
        "on-primary": "#490080",
        "primary-container": "#b76dff",
        "on-primary-container": "#400071",
        "primary-fixed": "#f0dbff",
        "primary-fixed-dim": "#ddb7ff",
        "on-primary-fixed": "#2c0051",
        "on-primary-fixed-variant": "#6900b3",
        "inverse-primary": "#842bd2",
        "secondary": "#7bd0ff",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        "on-secondary-container": "#00374d",
        "secondary-fixed": "#c4e7ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary": "#d0bcff",
        "on-tertiary": "#3c0091",
        "tertiary-container": "#a078ff",
        "on-tertiary-container": "#340080",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#23005c",
        "on-tertiary-fixed-variant": "#5516be",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        // Brand Overrides
        "plasma": {
          DEFAULT: "#a855f7",
          light: "#c084fc",
          dark: "#7e22ce",
        },
        "solar-cyan": "#38bdf8",
        "electric-violet": "#8b5cf6",
        "cosmic-obsidian": "#070814",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        display: ["'Space Grotesk'", "sans-serif"],
        headline: ["'Space Grotesk'", "sans-serif"],
        label: ["'Space Grotesk'", "sans-serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "gutter-lg": "2rem",
        "margin": "1.5rem",
        "margin-md": "3rem",
        "margin-lg": "5rem",
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '0.6', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.05)' },
        },
        radarSweep: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        }
      },
      animation: {
        float: 'float 4s ease-in-out infinite',
        pulseGlow: 'pulseGlow 3s ease-in-out infinite',
        radarSweep: 'radarSweep 6s linear infinite',
      }
    },
  },
  plugins: [],
}
